"""Add slug column to regions table

Revision ID: f09fb53ba77b
Revises: f58029841780
Create Date: 2025-07-09 17:33:22.158685

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f09fb53ba77b"
down_revision: Union[str, Sequence[str], None] = "f58029841780"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("regions", sa.Column("slug", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("regions", "slug")
    # ### end Alembic commands ###
