"""Add centroid and bounding box columns to regions and provinces

Revision ID: f58029841780
Revises: 355268b67c18
Create Date: 2025-07-09 16:55:32.145918

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f58029841780"
down_revision: Union[str, Sequence[str], None] = "355268b67c18"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("provinces", sa.Column("centroid_x", sa.Float(), nullable=True))
    op.add_column("provinces", sa.Column("centroid_y", sa.Float(), nullable=True))
    op.add_column("regions", sa.Column("centroid_x", sa.Float(), nullable=True))
    op.add_column("regions", sa.Column("centroid_y", sa.Float(), nullable=True))
    op.add_column("regions", sa.Column("bounding_box_sw_x", sa.Float(), nullable=True))
    op.add_column("regions", sa.Column("bounding_box_sw_y", sa.Float(), nullable=True))
    op.add_column("regions", sa.Column("bounding_box_ne_x", sa.Float(), nullable=True))
    op.add_column("regions", sa.Column("bounding_box_ne_y", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("regions", "bounding_box_ne_y")
    op.drop_column("regions", "bounding_box_ne_x")
    op.drop_column("regions", "bounding_box_sw_y")
    op.drop_column("regions", "bounding_box_sw_x")
    op.drop_column("regions", "centroid_y")
    op.drop_column("regions", "centroid_x")
    op.drop_column("provinces", "centroid_y")
    op.drop_column("provinces", "centroid_x")
    # ### end Alembic commands ###
